// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ElectronAppDebugger.d63e2777-d697-480f-839a-815d9f30a2c5";
        public const string Name = "Electron.NET Attach Debugger Extension";
        public const string Description = @"Just press F5 to debug your Electron.NET application. No need to switch to console, press `electronize start`, and then switch back to VS and attach. This is a Visual Studio extension.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "lsoft";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
